#!/usr/bin/env python
from rimudns import RimuDNS
import sys

api_key = 'ENTERKEY'

dns = RimuDNS(api_key)
dns.use_zonomi()

try:
	file = open(sys.argv[2], 'w')
except Exception:
	file = sys.stdout 

dns.to_file(sys.argv[1], file)
