#!/usr/bin/env python
from rimudns import RimuDNS
import sys, os

api_key = open(os.path.dirname(os.path.realpath(__file__)) + '/../.keyfile').read()

dns = RimuDNS(api_key)
dns.use_zonomi()

try:
	file = open(sys.argv[2], 'w')
except Exception:
	file = sys.stdout 

dns.to_file(sys.argv[1], file)
